apiVersion: apps/v1
kind: Deployment
metadata:
  name: author-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: author-manager
  template:
    metadata:
      labels:
        app: author-manager
    spec:
      containers:
        - name: author-manager
          image: author-manager
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 1
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: author-manager
  name: author-manager
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: author-manager
  type: NodePort

