apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name:  fail-github-books
  namespace: chaos-testing
spec:
  action: partition
  mode: all
  selector:
    namespaces:
      - default
    labelSelectors:
      "app": "book-manager"
  direction: to
  externalTargets:
    - "api.github.com"