apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-netem-example
  namespace: default
spec:
  action: netem
  mode: all
  selector:
    labelSelectors:
      "app": "author-manager"
  delay:
    latency: "3000ms"
  direction: both
  target:
    selector:
      labelSelectors:
        "app": "nats"
    mode: all