apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: delay-nats
  namespace: default
spec:
  action: netem
  mode: all
  selector:
    labelSelectors:
      "app": "author-manager"
  delay:
    latency: "6000ms"
  direction: from
  target:
    selector:
      labelSelectors:
        "app": "nats"
    mode: all